### ISSUE TITLE
TypeError: 'JOYO' object is not subscriptable

### ISSUE THREAD

**Issue by nonetrix** [ffe4/kanji-lists#14]
```
print(random.choice(JOYO))
```
returns
```
Traceback (most recent call last):
  File "/home/nonetrix/Projects/Python/twitter/src/./test.py", line 17, in <module>
    print(random.choice(JOYO))
  File "/usr/lib/python3.9/random.py", line 347, in choice
    return seq[self._randbelow(len(seq))]
TypeError: 'JOYO' object is not subscriptable
```
I know this is most likely due to me not understanding something

**Comment by ffe4** [comment]
Python's `random.choice` takes a sequence type, but `JOYO` is a `set`.
```pycon
>>> isinstance(JOYO, set)
True
>>> choice(set(['a', 'b']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Daniel/.pyenv/versions/3.9.1/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
TypeError: 'set' object is not subscriptable
```

You can just convert it to a list or tuple before using it.
```pycon
>>> joyo_kanji = tuple(JOYO)
>>> choice(joyo_kanji)
'返'
```

I will add a mention of the type to the README. It IS a bit confusing that a package called `kanji-lists` does not actually provide lists.

**Comment by nonetrix** [comment]
Thanks I didn't know about sets
